spring:
  datasource:
      username: root
      password: rootpass
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:Mysql://localhost:3306/course2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

